name: CI

on:
  pull_request:
  push:

jobs:
  build:
    name: Build exporter
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v1.'))
      ||
      (github.event_name == 'pull_request' && startsWith(github.event.pull_request.base.ref, 'release-'))
      ||
      (github.event_name == 'push' && github.event.ref == 'refs/heads/main')

    strategy:
      matrix:
        thread: [0, 1, 2, 3, 4]

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
      - uses: prometheus/promci@v0.1.0

      - uses: ./.github/promci/actions/build
        with:
          parallelism: 5
          thread: ${{ matrix.thread }}

  publish_main:
    name: Publish main branch artifacts
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: prometheus/promci@v0.1.0

      - uses: ./.github/promci/actions/setup_environment
        with:
          enable_docker_multibuild: true

      - uses: ./.github/promci/actions/restore_artifacts

      - uses: ./.github/promci/actions/publish_images
        with:
          registry: ghcr.io
          organization: solbound-dev
          login: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  publish_release:
    name: Publish release artifacts
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v1.')

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: prometheus/promci@v0.1.0

      - uses: ./.github/promci/actions/setup_environment
        with:
          enable_docker_multibuild: true

      - uses: ./.github/promci/actions/restore_artifacts

      - run: ~/go/bin/promu crossbuild tarballs
        shell: bash

      - run: ~/go/bin/promu checksum .tarballs
        shell: bash

      - run: ~/go/bin/promu release .tarballs
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/promci/actions/publish_release_images
        with:
          registry: ghcr.io
          organization: solbound-dev
          login: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
