name: Release

on:
  push:
    branches:
      - main

  release:
    types:
      - published

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Cross build for all platforms
        run: make crossbuild

      - name: Build docker images
        run: make docker

      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY: ghcr.io
        run: |
          echo "$DOCKER_PASSWORD" | docker login "$DOCKER_REGISTRY" --username "$DOCKER_USERNAME" --password-stdin

      - name: Publish docker images
        run: make docker-publish

      - name: Publish docker manifest
        run: make docker-manifest

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY: ghcr.io
        run: |
          echo "$DOCKER_PASSWORD" | docker login "$DOCKER_REGISTRY" --username "$DOCKER_USERNAME" --password-stdin

      - name: Tag docker latest
        run: make docker-tag-latest

      - name: Publish docker latest
        run: make docker-publish-latest

      - name: Publish docker manifest
        run: make docker-manifest-latest
